apiVersion: v1
kind: Pod
metadata:
  name: longhorn-pod
spec:
  volumes:
    - name: longhorn-storage
      persistentVolumeClaim:
        claimName: longhorn-pvc
  containers:
    - name: longhorn-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: longhorn-storage
