apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgresql-cluster
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgresql-cluster
  podMetricsEndpoints:
  - port: metrics
