apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: secrets
spec:
  containers:
    - name: app
      image: nginx:latest
      env:
        - name: MYSQL_DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: DB_USER
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
               name: secret-demo
               key: DB_PASS
      ports:
        - containerPort: 80 
